[workspace]
resolver = "2"
members = ["template", "day1", "day2"]

[workspace.dependencies]
itertools = "0.12.0"
rayon = "1.8.0"
glam = "0.24.2"
petgraph = "0.6.4"
indoc = "2.0.4"
fancy-regex = "0.12.0"
