[package]
name = "parse_grid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette.workspace = true
indoc.workspace = true
petgraph.workspace = true
thiserror = "1.0.50"
